export const siteCopy = {
  pl: {
    locale: "pl",
    nav: ["Jak grać", "ZOBACZ", "Premium"],
    headerCta: "Pobierz grę",
    heroTag: "BIBLIJNY IMPOSTOR • GRA TOWARZYSKA 13+",
    heroTitle: "Kto zna hasło, a kto tylko dobrze udaje?",
    heroLead: "Jedno biblijne hasło. Jedna osoba bez odpowiedzi. Podawajcie skojarzenia, obserwujcie reakcje i odkryjcie impostora, zanim on odkryje hasło.",
    comingSoon: "WKRÓTCE W",
    releaseNote: "Premiera w przygotowaniu. Zostaw tę stronę w zakładkach.",
    sticker: ["3–12 OSÓB", "JEDEN TELEFON"],
    rulesTag: "ZASADY W 60 SEKUND",
    rulesTitle: ["Prosta do wyjaśnienia.", "Trudna do rozgryzienia."],
    steps: [
      ["Poznaj swoją rolę", "Każdy widzi hasło. Jedna osoba dostaje tylko podpowiedź i musi się nie zdradzić."],
      ["Podaj skojarzenie", "Mów wystarczająco konkretnie, by przekonać innych, ale nie pomagaj impostorowi."],
      ["Zagłosujcie", "Wskażcie podejrzaną osobę. Jeśli traficie, impostor ma jeszcze szansę odgadnąć hasło."],
    ],
    screenshotsTag: "ZOBACZ GRĘ",
    screenshotsTitle: ["Telefon krąży.", "Podejrzenia rosną."],
    screenshotsNote: "Przesuń, aby zobaczyć kolejne ekrany →",
    screenshotAlts: ["Jedna osoba nie zna hasła", "Każdy zna hasło. Prawie każdy", "Jedno skojarzenie może Cię zdradzić", "Głosowanie na impostora", "450 biblijnych haseł", "Pełna wersja bez abonamentu"],
    featuresTag: "GRA DLA KAŻDEJ EKIPY",
    featuresTitle: ["450 biblijnych haseł.", "Zero nudnych rund."],
    featuresText: "Postacie, miejsca, wydarzenia i symbole. Od tych dobrze znanych po takie, które wyciągają na światło prawdziwych znawców.",
    stats: [["3", "poziomy trudności"], ["3–12", "osób przy jednym telefonie"], ["3", "wersje językowe: PL, EN i ES"], ["13+", "dla młodzieży i dorosłych"]],
    premiumTag: "PEŁNA WERSJA ATONI",
    premiumTitle: ["Jedna płatność.", "Graj bez limitu."],
    premiumBenefits: ["pełna baza 450 haseł", "wszystkie poziomy trudności", "bez abonamentu"],
    charity: "zysku ze sprzedaży ATONI Premium przeznaczamy na cele charytatywne.",
    finalTag: "GOTOWI NA PIERWSZĄ RUNDĘ?",
    finalTitle: "Jedna osoba nie zna hasła.",
    finalText: "A reszta nie może dać po sobie poznać, że je zna.",
    footerText: "Biblijna gra towarzyska na iOS i Androida.",
    privacy: "Polityka prywatności",
    terms: "Regulamin",
    rights: "Wszystkie prawa zastrzeżone.",
  },
  en: {
    locale: "en",
    nav: ["How to play", "Screenshots", "Premium"],
    headerCta: "Get the game",
    heroTag: "BIBLE IMPOSTOR • PARTY GAME 13+",
    heroTitle: "Who knows the word, and who is only pretending?",
    heroLead: "One Bible word. One player without the answer. Share clues, watch every reaction and expose the impostor before they discover the word.",
    comingSoon: "COMING SOON ON",
    releaseNote: "The launch is coming. Bookmark this page and stay close.",
    sticker: ["3–12 PLAYERS", "ONE PHONE"],
    rulesTag: "RULES IN 60 SECONDS",
    rulesTitle: ["Easy to explain.", "Hard to figure out."],
    steps: [
      ["Discover your role", "Everyone sees the word. One player gets only a clue and must avoid giving themselves away."],
      ["Give one association", "Be specific enough to convince the group, but do not help the impostor."],
      ["Vote together", "Point to the most suspicious player. If you are right, the impostor still gets one chance to guess the word."],
    ],
    screenshotsTag: "SEE THE GAME",
    screenshotsTitle: ["The phone moves.", "Suspicion grows."],
    screenshotsNote: "Swipe to see more screens →",
    screenshotAlts: ["One player does not know the word", "Everyone knows the word. Almost everyone", "One association can give you away", "Vote for the impostor", "450 Bible-themed words", "Full version with no subscription"],
    featuresTag: "MADE FOR EVERY GROUP",
    featuresTitle: ["450 Bible-themed words.", "No boring rounds."],
    featuresText: "People, places, events and symbols. From familiar stories to details that reveal who really knows their Bible.",
    stats: [["3", "difficulty levels"], ["3–12", "players with one phone"], ["3", "languages: PL, EN and ES"], ["13+", "for teens and adults"]],
    premiumTag: "THE FULL ATONI EXPERIENCE",
    premiumTitle: ["One payment.", "Play without limits."],
    premiumBenefits: ["all 450 Bible-themed words", "every difficulty level", "no subscription"],
    charity: "of the profit from ATONI Premium sales goes to charitable causes.",
    finalTag: "READY FOR THE FIRST ROUND?",
    finalTitle: "One player does not know the word.",
    finalText: "Everyone else must avoid making it too obvious that they do.",
    footerText: "A Bible-themed party game for iOS and Android.",
    privacy: "Privacy policy",
    terms: "Terms of use",
    rights: "All rights reserved.",
  },
  es: {
    locale: "es",
    nav: ["Cómo jugar", "Capturas", "Premium"],
    headerCta: "Descargar juego",
    heroTag: "IMPOSTOR BÍBLICO • JUEGO DE FIESTA 13+",
    heroTitle: "¿Quién conoce la palabra y quién solo finge?",
    heroLead: "Una palabra bíblica. Una persona sin la respuesta. Dad pistas, observad cada reacción y descubrid al impostor antes de que adivine la palabra.",
    comingSoon: "PRÓXIMAMENTE EN",
    releaseNote: "El lanzamiento está en camino. Guarda esta página en tus favoritos.",
    sticker: ["3–12 JUGADORES", "UN TELÉFONO"],
    rulesTag: "REGLAS EN 60 SEGUNDOS",
    rulesTitle: ["Fácil de explicar.", "Difícil de descubrir."],
    steps: [
      ["Descubre tu papel", "Todos ven la palabra. Una persona recibe solo una pista y debe evitar delatarse."],
      ["Da una asociación", "Sé lo bastante concreto para convencer al grupo, pero no ayudes al impostor."],
      ["Votad juntos", "Señalad a la persona más sospechosa. Si acertáis, el impostor aún puede intentar adivinar la palabra."],
    ],
    screenshotsTag: "DESCUBRE EL JUEGO",
    screenshotsTitle: ["El teléfono circula.", "Las sospechas crecen."],
    screenshotsNote: "Desliza para ver más pantallas →",
    screenshotAlts: ["Una persona no conoce la palabra", "Todos conocen la palabra. Casi todos", "Una asociación puede delatarte", "Votación del impostor", "450 palabras bíblicas", "Versión completa sin suscripción"],
    featuresTag: "PARA CUALQUIER GRUPO",
    featuresTitle: ["450 palabras bíblicas.", "Ninguna ronda aburrida."],
    featuresText: "Personajes, lugares, acontecimientos y símbolos. Desde historias conocidas hasta detalles que revelan quién conoce realmente la Biblia.",
    stats: [["3", "niveles de dificultad"], ["3–12", "personas con un teléfono"], ["3", "idiomas: PL, EN y ES"], ["13+", "para jóvenes y adultos"]],
    premiumTag: "LA EXPERIENCIA ATONI COMPLETA",
    premiumTitle: ["Un solo pago.", "Juega sin límites."],
    premiumBenefits: ["las 450 palabras bíblicas", "todos los niveles de dificultad", "sin suscripción"],
    charity: "de los beneficios de ATONI Premium se destina a fines benéficos.",
    finalTag: "¿LISTOS PARA LA PRIMERA RONDA?",
    finalTitle: "Una persona no conoce la palabra.",
    finalText: "Las demás no pueden dejar ver demasiado que sí la conocen.",
    footerText: "Un juego bíblico de fiesta para iOS y Android.",
    privacy: "Política de privacidad",
    terms: "Condiciones de uso",
    rights: "Todos los derechos reservados.",
  },
} as const;

export type SiteLocale = keyof typeof siteCopy;
export type SiteCopy = (typeof siteCopy)[SiteLocale];
